Patch readme somewhat
kozalosev/DeskChan-Launcher pull request #1
Opened 2017-12-21 00:36 UTC by Altai-man

Stopped around "FUTURE" section this time.

Could be better as I'm not a native one, but patched some of the most irritating mistakes.

Correct me if there's something I've misunderstood. Tried to leave the original writing style as is, though I'd made the text a bit more concise.

2018-01-06 12:43 UTC, kozalosev requested changes
Sorry for not answering for such a long time. I didn't know that I'd had to tick a special checkbox in the settings to get notifications about my own repositories automatically. It was the first reason. The second one was just my laziness to write another piece of text in bad English 😊 The third was the holidays, of course.

Thanks for correcting me and contributing to the project! However, we _[some members of the DC chat in Telegram]_ discussed the edits a bit, and I have some additional remarks and counter corrections.

I'd not like to be a grammar Nazi, but I just try to understand the English grammar and write as correctly as I know (not so good though). Would be glad to hear your objectives or any thoughts on my suggestions.

_Happy New Year!_

2018-01-06 12:43 UTC, kozalosev commented on README.md
> +An application that downloads DeskChan instance and keeps it up to date.
> An application that downloads **a** DeskChan instance...

2018-01-06 12:43 UTC, kozalosev commented on README.md
> +   - `plugins` directory with third-party plugins.
This is not quite true. There are both types of plugins in that directory: some made by DeskChan team, the others by third-party developers. I meant that only the latter group shouldn't be deleted, not the entire directory.

2018-01-06 12:43 UTC, kozalosev commented on README.md
> +2. Amazing! The application updates automatically! What a crazy thing!
Here opinion was divided between us _[people in the DC chat]_. My first point is that the application in this context is DeshChan, and it doesn't update itself. It uses the launcher for that instead. Hence, the passive tense is right. The second point, which is only mine own, is that there is a _process_ here. The updating doesn't finish in a moment, does it? It takes some time. Because of that, I've chosen the Present Continuous Passive tense. Nevertheless, I don't insist that I'm right, but I'm trying to understand what would be the most grammatically correct variant.

2018-01-06 12:43 UTC, kozalosev commented on README.md
> +Unfortunately, the launcher is not working in this way now. Currently, it's only able to:
> Unfortunately, the launcher is not working in this way **for** now.

I tried to avoid repetition of the word "now" everywhere and may have overdone it (but I still don't understand the difference between "now" and "today" as a synonym of "nowadays" here). However, I suggest prepending with "for" to emphasize the temporality of the situation.

2018-01-06 12:43 UTC, kozalosev commented on README.md
> +Command line module can be considered as more stable and has more features compared to the GUI one.
> **The c**ommand line module can be considered as more stable...

2018-01-06 12:43 UTC, kozalosev commented on README.md
> +#### Graphic user interface module
> Graphic**al** user interface module

[Proof.](https://en.wikipedia.org/wiki/Graphical_user_interface)

2018-01-06 12:43 UTC, kozalosev commented on README.md
> +As usual it supports command line arguments that allow users to configure various aspects of the launcher's work, listed below:
> As usual<b>,</b> it supports command line arguments<b>,</b> that allow users to configure various aspects of the launcher's work, listed below

I've added commas here.

2018-01-06 15:32 UTC, Altai-man commented on README.md
> +#### Graphic user interface module
Good catch, thanks.

2018-01-06 15:49 UTC, Altai-man commented on README.md
> +   - `plugins` directory with third-party plugins.
Hmmm. In this case we need to somehow introduce it firstly with a clause of type `If you have installed third-party plugins, omit them, otherwise delete`. I am not sure it can be described in one sentence fine enough right now, so I'll think about it more carefully later.

2018-01-06 15:51 UTC, Altai-man commented on README.md
> +As usual it supports command line arguments that allow users to configure various aspects of the launcher's work, listed below:
To be honest, not\_enough\_native\_for\_this\_one.jpg
I'll go with commas then.

2018-01-06 16:01 UTC, Altai-man commented on README.md
> +Unfortunately, the launcher is not working in this way now. Currently, it's only able to:
Well, you can say it's my gut feeling or something like that, as I talk with native folks every day. However, I agree that `for now` can be used too, this way it'd be even slightly better, I guess.

2018-01-06 16:10 UTC, Altai-man commented on README.md
> +2. Amazing! The application updates automatically! What a crazy thing!
1)I guess we can clarify the ambiguity by the use of `DeskChan` instead of `The application`.
2)Not sure about your time-related point. I'll ask some native folks at work closely to Monday and prepare the PR update.

2018-01-06 16:46 UTC, Altai-man commented on README.md
> +2. Amazing! The application updates automatically! What a crazy thing!
Oh, never mind me. If the subject is DeskChan, then, of course, `is being updated` is more correct.

2018-01-12 18:09 UTC, Altai-man commented
ping @kozalosev 

The week was totally insane, but got some minutes for this one, hence review is needed. Thanks.

2018-01-16 02:53 UTC, kozalosev approved these changes

2018-01-16 02:54 UTC, kozalosev commented
> The week was totally insane

Totally agree 😊

2018-01-16 03:02 UTC, merged